name: SBOM Pipeline with files

on: [push]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run:  SYFT_FORMAT_SPDX_JSON_PRETTY=true syft . -o spdx-json > sbom.json

      - name: Install Grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan and Sort Vulnerabilities
        run: |
          # Run grype and output results in JSON format
          grype sbom:sbom.json --output json > vulnerabilities-unsorted.json
          # Use jq to sort the vulnerabilities by severity.
          # This mapping assigns a numeric value to each severity level:
          # Critical: 4, High: 3, Medium: 2, Low: 1, others: 0.
          jq '.matches |= sort_by(
               (if .vulnerability.severity == "Critical" then 4
                elif .vulnerability.severity == "High" then 3
                elif .vulnerability.severity == "Medium" then 2
                elif .vulnerability.severity == "Low" then 1
                else 0 end)
              ) | .matches |= reverse' vulnerabilities-unsorted.json > vulnerabilities.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
          retention-days: 30

      - name: Upload Vulnerability Report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerabilities
          path: vulnerabilities.json
          retention-days: 30