name: SBOM Pipeline

on: [push]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run:  SYFT_FORMAT_SPDX_JSON_PRETTY=true SYFT_JAVASCRIPT_INCLUDE_DEV_DEPENDENCIES=true  syft . -o spdx-json > sbom.json

      - name: Install Grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Vulnerabilities
        run: grype sbom:sbom.json > vulnerabilities.txt

      - name: Upload SBOM (Local)
        if: ${{ env.ACT }}
        run: cat sbom.json

      - name: Upload SBOM (GitHub)
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
          retention-days: 30

      - name: Upload Vulnerability Report
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: vulnerabilities
          path: vulnerabilities.txt
          retention-days: 30